// Tests for PgTableDDLBuilder — catalog rows in, CREATE script out.

import XCTest
@testable import PgAgentApp

final class PostgresTableDDLTests: XCTestCase {

    private func column(
        _ name: String,
        _ type: String,
        notNull: Bool = false,
        defaultExpr: String? = nil,
        identity: String = "",
        generated: String = "",
        comment: String? = nil
    ) -> PgTableDDLColumn {
        PgTableDDLColumn(
            name: name,
            typeName: type,
            notNull: notNull,
            defaultExpr: defaultExpr,
            identity: identity,
            generated: generated,
            comment: comment
        )
    }

    func testBuildsPlainTableWithConstraintsAndIndexes() {
        let ddl = PgTableDDLBuilder.build(
            PgTableDDLInput(
                schema: "public",
                table: "users",
                columns: [
                    column("id", "integer", notNull: true, identity: "a"),
                    column("email", "text", notNull: true),
                    column(
                        "created_at", "timestamp with time zone",
                        defaultExpr: "now()"
                    ),
                ],
                constraints: [
                    ("users_pkey", "PRIMARY KEY (id)"),
                    ("users_email_key", "UNIQUE (email)"),
                ],
                indexes: ["CREATE INDEX users_created_idx ON public.users USING btree (created_at)"],
                tableComment: nil
            )
        )

        XCTAssertTrue(ddl.contains("CREATE TABLE \"public\".\"users\" ("))
        XCTAssertTrue(ddl.contains("\"id\" integer GENERATED ALWAYS AS IDENTITY NOT NULL"))
        XCTAssertTrue(ddl.contains("\"email\" text NOT NULL"))
        XCTAssertTrue(ddl.contains("\"created_at\" timestamp with time zone DEFAULT now()"))
        XCTAssertTrue(ddl.contains("CONSTRAINT \"users_pkey\" PRIMARY KEY (id)"))
        XCTAssertTrue(ddl.contains("CONSTRAINT \"users_email_key\" UNIQUE (email)"))
        XCTAssertTrue(
            ddl.contains("CREATE INDEX users_created_idx ON public.users USING btree (created_at);")
        )
        // Column entries are comma-separated, last body line is not.
        XCTAssertTrue(ddl.contains("NOT NULL,\n"))
        XCTAssertTrue(ddl.contains("UNIQUE (email)\n);"))
    }

    func testRendersGeneratedAndByDefaultIdentityColumns() {
        let ddl = PgTableDDLBuilder.build(
            PgTableDDLInput(
                schema: "s",
                table: "t",
                columns: [
                    column("seq", "bigint", notNull: true, identity: "d"),
                    column(
                        "total", "numeric",
                        defaultExpr: "(price * quantity)",
                        generated: "s"
                    ),
                ],
                constraints: [],
                indexes: [],
                tableComment: nil
            )
        )

        XCTAssertTrue(ddl.contains("\"seq\" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL"))
        XCTAssertTrue(ddl.contains("\"total\" numeric GENERATED ALWAYS AS ((price * quantity)) STORED"))
        // A generated column's attrdef expression must not ALSO render
        // as a DEFAULT clause.
        XCTAssertFalse(ddl.contains("DEFAULT (price * quantity)"))
    }

    func testQuotesHostileIdentifiersAndComments() {
        let ddl = PgTableDDLBuilder.build(
            PgTableDDLInput(
                schema: "we\"ird",
                table: "Order",
                columns: [
                    column("select", "text", comment: "it's a keyword")
                ],
                constraints: [],
                indexes: [],
                tableComment: "the \"orders\" table"
            )
        )

        XCTAssertTrue(ddl.contains("CREATE TABLE \"we\"\"ird\".\"Order\" ("))
        XCTAssertTrue(ddl.contains("\"select\" text"))
        XCTAssertTrue(
            ddl.contains("COMMENT ON TABLE \"we\"\"ird\".\"Order\" IS 'the \"orders\" table';")
        )
        XCTAssertTrue(
            ddl.contains(
                "COMMENT ON COLUMN \"we\"\"ird\".\"Order\".\"select\" IS 'it''s a keyword';")
        )
    }
}
