import Foundation
#if canImport(PgAgentMacOS)
import PgAgentMacOS
#endif

// =============================================================================
// PostgresTableDDL — assemble a CREATE TABLE script from catalog data.
//
// The builder is pure (rows in, SQL out) so it's unit-testable; `generate`
// runs the three catalog queries and feeds it. The output is an honest
// approximation for humans — column definitions, constraints, secondary
// indexes, and comments — not a byte-faithful pg_dump replacement (no
// storage parameters, tablespaces, ownership, or grants).
// =============================================================================

/// One column row from the catalog query, pre-parsed.
struct PgTableDDLColumn {
    let name: String
    /// `format_type` output, e.g. `character varying(80)`.
    let typeName: String
    let notNull: Bool
    /// `pg_get_expr` of the attrdef — a DEFAULT for plain columns,
    /// the generation expression for generated columns.
    let defaultExpr: String?
    /// `pg_attribute.attidentity`: "" / "a" (always) / "d" (by default).
    let identity: String
    /// `pg_attribute.attgenerated`: "" / "s" (stored).
    let generated: String
    let comment: String?
}

struct PgTableDDLInput {
    let schema: String
    let table: String
    let columns: [PgTableDDLColumn]
    /// `(conname, pg_get_constraintdef)` pairs, already ordered.
    let constraints: [(name: String, definition: String)]
    /// `pg_get_indexdef` strings for indexes NOT backing a constraint.
    let indexes: [String]
    let tableComment: String?
}

enum PgTableDDLBuilder {
    static func build(_ input: PgTableDDLInput) -> String {
        let qualified = "\(pgQuoteIdent(input.schema)).\(pgQuoteIdent(input.table))"
        var lines: [String] = []
        lines.append("-- DDL for \(qualified), generated from catalog metadata.")
        lines.append("-- Approximation for reading and re-creating the shape — storage")
        lines.append("-- parameters, ownership, grants, and triggers are not included.")
        lines.append("")

        var body: [String] = []
        for col in input.columns {
            var parts = ["\(pgQuoteIdent(col.name)) \(col.typeName)"]
            if col.generated == "s", let expr = col.defaultExpr {
                parts.append("GENERATED ALWAYS AS (\(expr)) STORED")
            } else if col.identity == "a" {
                parts.append("GENERATED ALWAYS AS IDENTITY")
            } else if col.identity == "d" {
                parts.append("GENERATED BY DEFAULT AS IDENTITY")
            } else if let expr = col.defaultExpr {
                parts.append("DEFAULT \(expr)")
            }
            if col.notNull {
                parts.append("NOT NULL")
            }
            body.append("    " + parts.joined(separator: " "))
        }
        for constraint in input.constraints {
            body.append("    CONSTRAINT \(pgQuoteIdent(constraint.name)) \(constraint.definition)")
        }

        lines.append("CREATE TABLE \(qualified) (")
        lines.append(body.joined(separator: ",\n"))
        lines.append(");")

        if !input.indexes.isEmpty {
            lines.append("")
            for index in input.indexes {
                lines.append("\(index);")
            }
        }

        var comments: [String] = []
        if let tc = input.tableComment {
            comments.append("COMMENT ON TABLE \(qualified) IS \(pgQuoteLiteral(tc));")
        }
        for col in input.columns {
            if let cc = col.comment {
                comments.append(
                    "COMMENT ON COLUMN \(qualified).\(pgQuoteIdent(col.name)) IS \(pgQuoteLiteral(cc));"
                )
            }
        }
        if !comments.isEmpty {
            lines.append("")
            lines.append(contentsOf: comments)
        }

        return lines.joined(separator: "\n") + "\n"
    }
}

/// Loader: three catalog round-trips, then the pure builder.
enum PostgresTableDDL {
    static func generate(
        connectionId: String, schema: String, table: String
    ) async throws -> String {
        let sessionId = "ddl-loader-\(UUID().uuidString)"
        defer {
            Task {
                await BridgeManager.shared.pgReleaseSession(
                    connectionId: connectionId, sessionId: sessionId)
            }
        }
        let regclassArg = pgQuoteLiteral(pgQuoteIdent(schema) + "." + pgQuoteIdent(table))

        let columnsSql = """
        SELECT a.attname,
               format_type(a.atttypid, a.atttypmod),
               a.attnotnull,
               pg_get_expr(ad.adbin, ad.adrelid),
               a.attidentity,
               a.attgenerated,
               col_description(a.attrelid, a.attnum)
        FROM pg_attribute a
        LEFT JOIN pg_attrdef ad ON ad.adrelid = a.attrelid AND ad.adnum = a.attnum
        WHERE a.attrelid = to_regclass(\(regclassArg))
          AND a.attnum > 0 AND NOT a.attisdropped
        ORDER BY a.attnum;
        """

        // Order: PK, unique, FK, check, then the exotic rest.
        // contype 'n' (named NOT NULL constraints, new in Postgres 18)
        // is excluded — the column lines already carry NOT NULL, and
        // the `CONSTRAINT … NOT NULL col` spelling doesn't parse on
        // older servers.
        let constraintsSql = """
        SELECT conname, pg_get_constraintdef(oid, true)
        FROM pg_constraint
        WHERE conrelid = to_regclass(\(regclassArg))
          AND contype <> 'n'
        ORDER BY CASE contype
                   WHEN 'p' THEN 0 WHEN 'u' THEN 1 WHEN 'f' THEN 2 WHEN 'c' THEN 3
                   ELSE 4
                 END, conname;
        """

        let indexesSql = """
        SELECT pg_get_indexdef(i.indexrelid)
        FROM pg_index i
        WHERE i.indrelid = to_regclass(\(regclassArg))
          AND NOT EXISTS (
            SELECT 1 FROM pg_constraint c WHERE c.conindid = i.indexrelid
          )
        ORDER BY 1;
        """

        let tableCommentSql = """
        SELECT obj_description(to_regclass(\(regclassArg)), 'pg_class');
        """

        func run(_ sql: String) async throws -> FfiPgExecutionResult {
            try await BridgeManager.shared.pgExecute(
                connectionId: connectionId,
                sessionId: sessionId,
                sql: sql,
                pageSize: 2000
            )
        }

        let columnsRes = try await run(columnsSql)
        let constraintsRes = try await run(constraintsSql)
        let indexesRes = try await run(indexesSql)
        let commentRes = try await run(tableCommentSql)

        let columns: [PgTableDDLColumn] = columnsRes.rows.compactMap { row in
            let c = row.cells
            guard c.count >= 7, let name = c[0], let type = c[1] else { return nil }
            return PgTableDDLColumn(
                name: name,
                typeName: type,
                notNull: c[2] == "t",
                defaultExpr: c[3],
                identity: c[4] ?? "",
                generated: c[5] ?? "",
                comment: c[6]
            )
        }
        guard !columns.isEmpty else {
            throw PostgresBridgeError.other(
                "Table \(schema).\(table) not found (or has no columns).")
        }
        let constraints: [(String, String)] = constraintsRes.rows.compactMap { row in
            guard row.cells.count >= 2, let n = row.cells[0], let d = row.cells[1] else {
                return nil
            }
            return (n, d)
        }
        let indexes: [String] = indexesRes.rows.compactMap { $0.cells.first ?? nil }
        let tableComment = commentRes.rows.first?.cells.first ?? nil

        return PgTableDDLBuilder.build(
            PgTableDDLInput(
                schema: schema,
                table: table,
                columns: columns,
                constraints: constraints,
                indexes: indexes,
                tableComment: tableComment
            )
        )
    }
}
