#!/usr/bin/env python3
"""PreToolUse safety guard for Claude Code — a feedforward harness control.

Turns this repo's documented footguns and a few universally-destructive shell
commands into hard, enforced rules. Every rule below traces to a real failure
class (see CLAUDE.md / AGENTS.md) — the "ratchet" pattern from
addyosmani.com/blog/agent-harness-engineering and
martinfowler.com/articles/harness-engineering.

Contract (Claude Code hook protocol):
  exit 0  -> allow, silently ("success is silent")
  exit 2  -> block; stderr is fed back to the agent ("failures are verbose")
  other   -> non-blocking error; the tool still runs (we fail OPEN on bad input)
"""
import json
import re
import sys


def block(msg: str) -> None:
    sys.stderr.write("⛔ Harness guard blocked this action.\n" + msg + "\n")
    sys.exit(2)


def guard_edit(file_path: str) -> None:
    path = (file_path or "").replace("\\", "/")

    # 1. UniFFI-generated bindings. Hand edits resolve at compile time but fail
    #    the runtime per-function checksum -> rshellInit() _assertionFailure crash.
    if (
        re.search(r"/bindings/.+\.(swift|h|modulemap)$", path)
        or re.search(r"midnight_ssh(FFI)?\.(swift|h)$", path)
        or path.endswith("module.modulemap")
    ):
        block(
            "`%s` is generated by UniFFI. Editing it causes an rshellInit "
            "checksum-mismatch crash at startup.\n"
            "→ Change `src/ffi.rs`, then run `just mac-bindings` and commit "
            "the regenerated bindings." % path
        )

    # 2. Xcode project is generated from project.yml by XcodeGen.
    if "/pgAgent.xcodeproj/" in path or path.endswith(".pbxproj"):
        block(
            "`%s` is generated from `project.yml` by XcodeGen and will be "
            "overwritten.\n→ Edit `project.yml`, then run `just mac-gen`." % path
        )


# rm -rf is allowed when it only targets regenerable build artifacts — these are
# the documented recovery steps in AGENTS.md, not destructive to source.
_SAFE_RM = re.compile(
    r"^(\./)?(build|\.build|\.derivedData|target|derivedData|"
    r"[\w./-]*\.xcodeproj|[\w./-]*SourcePackages|/tmp/[\w./-]+|/private/tmp/[\w./-]+)/?$"
)


def _rm_is_safe(command: str) -> bool:
    # Only exempt a single, unchained `rm`. Any &&/;/| means a second command
    # could hide — fall through to the block rule rather than risk it.
    if re.search(r"[;&|]|\$\(|`", command):
        return False
    toks = command.split()
    if not toks or toks[0] != "rm":
        return False
    targets = [t for t in toks[1:] if not t.startswith("-")]
    return bool(targets) and all(_SAFE_RM.match(t) for t in targets)


def guard_bash(command: str) -> None:
    cmd = command or ""
    low = cmd.lower()

    if re.search(r"\brm\s+(-\w*r\w*f|-\w*f\w*r)\b", low) and _rm_is_safe(cmd):
        return  # deleting only regenerable build dirs — allow

    rules = [
        (
            r"\brm\s+(-\w*r\w*f|-\w*f\w*r)\b",
            "recursive force `rm`. Confirm the exact target and delete narrowly "
            "instead of with -rf.",
        ),
        (
            r"\bgit\s+push\b[^|;&]*(--force\b|\s-f\b)",
            "force-push rewrites shared history. Push without --force, or use "
            "`--force-with-lease` only after confirming with a human.",
        ),
        (
            r"\bgit\s+reset\s+--hard\b",
            "`git reset --hard` discards uncommitted work. Stash or commit first.",
        ),
        (
            r"\bgit\s+clean\s+-\w*f",
            "`git clean -f` irreversibly deletes untracked files.",
        ),
        (
            r"(psql|mysql|sqlite3|cockroach|pg_dump)[^|;&]*\b(drop\s+(table|database|schema)|truncate\s+table)\b",
            "destructive SQL (DROP/TRUNCATE) against a live client. Keep queries "
            "read-only; mutate schema/data only with explicit human approval.",
        ),
        (
            r":\s*\(\s*\)\s*\{\s*:\s*\|\s*:&?\s*\}\s*;",
            "fork-bomb pattern.",
        ),
    ]
    for pattern, why in rules:
        if re.search(pattern, low):
            block("Destructive command — %s\nCommand: %s" % (why, cmd))


def main() -> None:
    try:
        data = json.load(sys.stdin)
    except Exception:
        sys.exit(0)  # fail open: never block on unparseable hook input

    tool = data.get("tool_name", "")
    tool_input = data.get("tool_input", {}) or {}

    if tool in ("Write", "Edit", "MultiEdit"):
        guard_edit(tool_input.get("file_path", ""))
    elif tool == "Bash":
        guard_bash(tool_input.get("command", ""))

    sys.exit(0)


if __name__ == "__main__":
    main()
